mpi ops& distributed batchnorm
Jittor/jittor pull request #58
Opened 2020-04-10 05:34 UTC by Gword

2020-04-19 15:07 UTC, cjld commented on extern/mpi/ops/mpi_reduce_op.cc
> +    for (index_t i=0; i<num; i++)
if (root != mpi_world_rank) for ....

2020-04-19 15:10 UTC, cjld commented on extern/mpi/ops/mpi_broadcast_op.cc
> +    MPI_Recv(yp, size, MPI_FLOAT, root, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
MPI_broadcast?

2020-04-19 15:20 UTC, cjld commented on extern/mpi/ops/mpi_broadcast_op.cc
> +    y->set_shape(x->shape);
```
if (root == mpi_world_rank)
  y->share_with(x);
```

2020-04-19 15:39 UTC, cjld commented on extern/mpi/ops/mpi_reduce_op.cc
> +    MPI_Reduce(xp, yp, size, MPI_FLOAT, MPI_SUM, root, MPI_COMM_WORLD);
支持多种类型，
参考https://github.com/Jittor/jittor/pull/57/files#diff-52bb7f0a5beaae1676a30579a7361f3bR46

2020-04-22 07:59 UTC, cxjyxxme requested changes

2020-04-22 07:59 UTC, cxjyxxme commented on python/jittor/nn.py
> +                x2mean =  jt.compile_extern.mpi_ops.mpi_all_reduce(x2mean)/jt.compile_extern.mpi.world_size()
不同进程的batch数量可能不一样，好像不能直接除

2020-04-22 07:59 UTC, cxjyxxme commented on python/jittor/test/test_mpi_batchnorm.py
> +    def test_batchnorm(self):
加个测试下不同进程batchsize不一样的case

2020-04-22 08:54 UTC, cjld commented on extern/mpi/ops/mpi_all_reduce_op.cc
> +        @if(@strcmp(@OP,add)==0, MPI_SUM)
MPI_MIN,MPI_MAX may added in the future

2020-04-22 08:54 UTC, cjld commented on extern/mpi/ops/mpi_all_reduce_op.cc
> +    ASSERT(x->dtype().is_float());
forget to remove, removed now

2020-04-22 08:55 UTC, cjld commented on extern/mpi/ops/mpi_all_reduce_op.cc
> +    add_jit_define("OP", op.to_cstring());
MPI_MIN,MPI_MAX may added in the future

2020-04-22 11:59 UTC, cxjyxxme approved these changes

2020-04-22 12:31 UTC, merged